language: java

sudo: false
dist: trusty

install: echo "Don't let Travis CI execute './gradlew assemble' by default"

matrix:
  include:
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12
  - jdk: openjdk13
  - jdk: openjdk-ea
  allow_failures:
  - jdk: openjdk-ea

env:
  global:
    - secure: HU0QOLEDkYHcjX+PkicGGQ5g2L1/19V2fH13OSn82DOFlIiWmCfhSI8EG/QoWwPDp/HYQ4DH5Lo+ZEhVz5tgEultItyJ38LZJl/YYOzSAiRvTezmDdz+Cdg6SXAwCvgFCTagEJ1ChL5NyenDGDlwPB/drN0HlNNU6igPqNkM8l0=
    - secure: VByzrX+inH3Z2nq50Hkj1FJnyOjPdsdIo/RUcl6DxUjkYfXP0n3tkPZGFA0PwiDpEwvRcSGLMR7mJ59Bhja5wgqXNhMqV4F0kB2PEFHSC3UmkyMnTSmDBKvP2aT6JLq00K3mYeNV5HiaYV4S7UVNdzZwaPCgc2aVZN8hF4f5/V8=
    - secure: GWvKpGPBF1b/2tkYzJ/IwKpGd3kjfYpadIFoQOdQS3r6iZkutZ9FhW6vINIRsgcIRHTVha0BywG7m5sJIYo/jmsDbXc2VJFO7EcXkK6k96VZYb0pHjbXqeP/u9/ZfSzeQ4w3qNYUiXztmmrLjbCzG2gV4D2CqOaug2o81mVj4LI=
    - secure: m91QxOLHBRnJzRyphCivL79i90pE/FO4yg8qTOaDuyTqVXBKnHmdARFOxSMZN9Qn3B3e28xxPaazIsJGCuPXiQKSObqzPLeFHUOa3atUJSckEUW623l1313A9iMFOYbqSBAHFHmiuuAJBwN/E2OnG3BcLZV1FRibW6J1qLRLdJw=
    - secure: lQRKL++CN8U33UT8h/EMxFxCSVlUdbZy7/BwN8evbf351lAPI0URONB9LcTKvDvGLlDGaGxOUC6fj8SYAxrv0B9znLVIefA62ttzI0/+ztWyJalJk3z2EVaNA5jgMPi6KGI0bbh8mygHN0Esx1KxvfykAf/ZJOZD3OKeQ45KaKJNamMDHRRdQzRuQK9+sfY255e5GG6Nzv++8krGeeSYO5qVOoSVBLbtHMG1rr8Fi7VxX2LZJgi+ZUAowEaNWDVIreLE0p1rNCBpD/ngxa7vS3neWC3GiRBhGKzxXIoWP1Fly4ARAyij+ssI8Rc2mW1jqvu/EqNjWMbCA1LWm4HJDXrcf+2uWlVh9F5cssXnDcM6NJ4OEx7naCKo/QOloqJRonqveDGtiLg02LuxQYNMgobTjn8PeGC98Eh+QgcmqIvNSUoGPVWFBM/rPOgUEe2o5+n5TnqALGycZr6XaVB+EGSrlBwhIBTtUZ0HTIwWyx4wVfptKAu42nArEeUL6N2fVm9ajyltHKRIhmed8+oeZDqVWPy6BOTyS3QUes6bGXcgNGcCvFYouaEPs3nlBD8gG3HT9izNvSukMo0vRynPMO10G/W7IeYXs8ttm39JFq3sBGO4cSVmBvYNzkL4WIMGApOGvcdQrGsPzBK/8dyjslw4CxB/LXvSFUc/+NVF3TE=

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.4"

before_install:
  - unset _JAVA_OPTIONS
  - export M2_HOME=$HOME/apache-maven-3.5.4
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH

script: mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean deploy -DskipTests --settings .travis/maven-settings.xml
